### ISSUE TITLE
Problem with dish looping (the app does not load when on the last dish, but will loop to the first dish the next day)

### ISSUE THREAD

**Issue by Axiomatic314** [Axiomatic314/COSC345#21]
On the day after the last dish, the app will not load anything - but will load the first dish on the following day.

Either there is a gap in the looping, or there is an error with the last dish in the database.

**Comment by Bugbie** [comment]
> On the day after the last dish, the app will not load anything - but will load the first dish on the following day.
> 
> Either there is a gap in the looping, or there is an error with the last dish in the database.

The last dish is the one that doesn't load. The app correctly loops back to the first the day after the last dish is meant to be played
